name: ESLint

on:
  pull_request:
    branches: [main, heroku]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint