name: Update Request

on:
  pull_request:
    types: [closed]
    branches: [heroku]
  workflow_dispatch:
    branches: [heroku]


jobs:
  update:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        id: request
        uses: tyrrrz/action-http-request@master
        with:
          url: ${{vars.FRONTEND_UPDATE_ENDPOINT}}
          method: POST
          headers: |
            Content-Type: application/json
          body: |
            {
              "FRONTEND_UPDATE_REQUEST_TOKEN": "${{secrets.FRONTEND_UPDATE_REQUEST_TOKEN}}"
            }

      - name: Print outputs
        run: |
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"